apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: s3zipper  
spec:
  selector:
    app: mongo
    tier: db
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3zipper-mongodb
  namespace: s3zipper  
  labels:
    app: s3zipper-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      tier: db
  template:
    metadata:
      labels:
        app: mongo
        tier: db
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.10
        imagePullPolicy: IfNotPresent 
        command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        - "--port"
        - "27017"      
        ports:
          - name: mongo
            containerPort: 27017
        volumeMounts:
          - name: mongodb-persistent-volume
            mountPath: /data/db
      volumes:
        - name: mongodb-persistent-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
