apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zipper-pvc
  namespace: s3zipper
  labels:
    app: s3zipper
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi



