apiVersion: v1
kind: Service
metadata:
  name: s3zipper
  namespace: s3zipper  
spec:
  selector:
    app: s3zipper
    tier: app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3zipper
  namespace: s3zipper   
  labels:
    app: s3zipper
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3zipper
      tier: app
  template:
    metadata:
      labels:
        app: s3zipper
        tier: app
    spec:
      imagePullSecrets:
      - name: s3zippercreds  #This needs to be created to be able to pull image from the ECR repository below   
      containers:
      - name: s3zipper
        image: 709825985650.dkr.ecr.us-east-1.amazonaws.com/s3zipper/zipperimages:1.2.5 #this repo needs s3zippercreds to work
        imagePullPolicy: Always   # To be pulled from remote registry. 
        #imagePullPolicy: Never   # So it doesn't pull the image from remote registry.
   
        ports:
          - name: s3zipper
            containerPort: 80
        volumeMounts:
          - name: zipper-persistent-volume
            mountPath: /home/go/zipdata  # This volume is needed for temporary files.
      volumes:
        - name: zipper-persistent-volume
          persistentVolumeClaim:
            claimName: zipper-pvc
